language: ruby
rvm:
  - 1.9.3
  - 2.1.2
  - rbx
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx
cache: 
  - bundler
  - apt
before_install:
  - sudo apt-get update
  - sudo apt-get install -qq ffmpeg aria2 wget curl
